-- Revision History:
-- 		   DATE 			NAME					COMMENTS
--		2025-05-31		DERRICK MANGARI		CREATED QUERY TO CREATE TABLES

-- create necessary enums
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
        CREATE TYPE task_status AS ENUM ('in-progress', 'completed');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_priority') THEN
        CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high');
    END IF;
END$$;

-- Create users table
CREATE TABLE IF NOT EXISTS USERS (
	USER_ID UUID PRIMARY KEY,
	USERNAME VARCHAR(15) NOT NULL UNIQUE,
	EMAIL VARCHAR(120) NOT NULL UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create tags table
CREATE TABLE IF NOT EXISTS TAGS (
	TAG_ID UUID PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	COLOR VARCHAR(7) NOT NULL,
	USER_ID UUID NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
	UNIQUE (user_id, name)
);


-- Create tasks table
CREATE TABLE IF NOT EXISTS TASKS (
	TASK_ID UUID PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	STATUS TASK_STATUS NOT NULL,
	DUE_DATE TIMESTAMP,
	PRIORITY TASK_PRIORITY NOT NULL,
	RECURRING_TASK BOOLEAN NOT NULL,
	NOTIFICATION_REMINDER BOOLEAN NOT NULL,
	NOTIFICATION_DATE TIMESTAMP,
	REMINDER_TIME VARCHAR(10),
	TAG_ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (TAG_ID) REFERENCES TAGS (TAG_ID) ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
);

--Create subtasks table
CREATE TABLE IF NOT EXISTS SUBTASKS (
	SUBTASK_ID UUID PRIMARY KEY,
	TASK_ID UUID NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	IS_DONE BOOLEAN NOT NULL,
	DUE_DATE TIMESTAMP,
	NOTIFICATION_REMINDER BOOLEAN NOT NULL,
	NOTIFICATION_DATE TIMESTAMP,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (TASK_ID) REFERENCES TASKS (TASK_ID) ON DELETE CASCADE
);